default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: prashu
  password: prashu123
  host: localhost

development:
  <<: *default
  database: weather_forecast_development

test:
  <<: *default
  database: weather_forecast_test
